# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  default:
    desc: Compile the STM32 static library for both cores
    cmds:
      - task: build-m4-static
      - task: build-m7-static
  build-m4-static:
    env:
      ARCH_NUMBER: "4"
      EXTRA_FLAG: "-mfpu=fpv4-sp-d16"
    desc: Compile the STM32 static library for M4
    sources:
      - "*.c"
    generates:
      - ../CM4/libs/stm32h7xx.a
    cmds:
      - mkdir -p ../CM"$ARCH_NUMBER"/libs
      - defer: rm *.o
      - for: sources
        cmd: arm-none-eabi-gcc -c "{{.ITEM}}" -o "{{.ITEM}}.o" -mcpu=cortex-m"$ARCH_NUMBER" -mthumb -mfloat-abi=softfp "$EXTRA_FLAG" -DCORE_CM"$ARCH_NUMBER" -DSTM32H747xx -DUSE_FULL_LL_DRIVER -I./include -I../CM"$ARCH_NUMBER"/include -Os -g
      - arm-none-eabi-gcc -c ./startup_stm32h747xx.s -o startup_stm32h747xx.o -mcpu=cortex-m"$ARCH_NUMBER" -mthumb
      - arm-none-eabi-ar rcs ../CM"$ARCH_NUMBER"/libs/stm32h7xx.a ./*.o
  build-m7-static:
    env:
      ARCH_NUMBER: "7"
      EXTRA_FLAG: "-mfpu=fpv5-d16"
    desc: Compile the STM32 static library for M7
    sources:
      - "*.c"
    generates:
      - ../CM4/libs/stm32h7xx.a
    cmds:
      - mkdir -p ../CM"$ARCH_NUMBER"/libs
      - defer: rm *.o
      - for: sources
        cmd: arm-none-eabi-gcc -c "{{.ITEM}}" -o "{{.ITEM}}.o" -mcpu=cortex-m"$ARCH_NUMBER" -mthumb -mfloat-abi=softfp "$EXTRA_FLAG" -DCORE_CM"$ARCH_NUMBER" -DSTM32H747xx -DUSE_FULL_LL_DRIVER -I./include -I../CM"$ARCH_NUMBER"/include -Os -g
      - arm-none-eabi-gcc -c ./startup_stm32h747xx.s -o startup_stm32h747xx.o -mcpu=cortex-m"$ARCH_NUMBER" -mthumb
      - arm-none-eabi-ar rcs ../CM"$ARCH_NUMBER"/libs/stm32h7xx.a ./*.o
