# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  default:
    deps:
      - build-static-m4
      - build-static-m7
    desc: Compile the STM32 static library for both cores
  build-static-m4:
    desc: Build the static library for the M4 core
    cmds:
      - task: build-static
        vars:
          ARCH_NUMBER: "4"
          EXTRA_FLAG: "-mfpu=fpv4-sp-d16"
  build-static-m7:
    desc: Build the static library for the M7 core
    cmds:
      - task: build-static
        vars:
          ARCH_NUMBER: "7"
          EXTRA_FLAG: "-mfpu=fpv5-d16"
  build-static:
    desc: Build the static library for the M{{.ARCH_NUMBER}} core
    internal: true
    vars:
      ARCH_NUMBER: '{{default "4" .ARCH_NUMBER}}'
      EXTRA_FLAG: '{{default "-mfpu=fpv4-sp-d16" .EXTRA_FLAG}}'
    sources:
      - "*.c"
      - "./include/*.h"
      - "./include/Legacy/*.h"
    generates:
      - ../CM{{.ARCH_NUMBER}}/libs/stm32h7xx.a
    cmds:
      - mkdir -p ../CM{{.ARCH_NUMBER}}/libs
      - defer: rm *_m{{.ARCH_NUMBER}}.o
      - cmd: |-
          set -exu
          for file in *.c; do
          arm-none-eabi-gcc -c "$file" -o "${file%.c}_m{{.ARCH_NUMBER}}.o" \
              -mcpu=cortex-m{{.ARCH_NUMBER}} -mthumb -mfloat-abi=softfp \
              {{.EXTRA_FLAG}} \
              -I./include -I../CM{{.ARCH_NUMBER}}/include -Os -g \
              -DCORE_CM{{.ARCH_NUMBER}} -DSTM32H747xx -DUSE_FULL_LL_DRIVER
          done
      - arm-none-eabi-gcc -c ./startup_stm32h747xx.s -o startup_stm32h747xx_m{{.ARCH_NUMBER}}.o -mcpu=cortex-m{{.ARCH_NUMBER}} -mthumb
      - arm-none-eabi-ar rcs ../CM{{.ARCH_NUMBER}}/libs/stm32h7xx.a ./*_m{{.ARCH_NUMBER}}.o
