# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  default:
    desc: Compile the STM32 static library for both cores
    cmds:
      - task: build-static
        vars:
          ARCH_NUMBER: "4"
          EXTRA_FLAG: "-mfpu=fpv4-sp-d16"
      - task: build-static
        vars:
          ARCH_NUMBER: "7"
          EXTRA_FLAG: "-mfpu=fpv5-d16"
  build-static:
    vars:
      ARCH_NUMBER: '{{default "4" .ARCH_NUMBER}}'
      EXTRA_FLAG: '{{default "-mfpu=fpv4-sp-d16" .EXTRA_FLAG}}'
    desc: Compile the STM32 static library for some architecture specified in variables
    sources:
      - "*.c"
      - "./include/*.h"
      - "./include/Legacy/*.h"
    generates:
      - ../CM{{.ARCH_NUMBER}}/libs/stm32h7xx.a
    cmds:
      - mkdir -p ../CM{{.ARCH_NUMBER}}/libs
      - defer: rm *.o
      - cmd: |-
          set -exu
          for file in *.c; do
            arm-none-eabi-gcc -c "$file" -o "$file.o" -mcpu=cortex-m{{.ARCH_NUMBER}} -mthumb -mfloat-abi=softfp {{.EXTRA_FLAG}} -DCORE_CM{{.ARCH_NUMBER}} -DSTM32H747xx -DUSE_FULL_LL_DRIVER -I./include -I../CM{{.ARCH_NUMBER}}/include -Os -g
          done
      - arm-none-eabi-gcc -c ./startup_stm32h747xx.s -o startup_stm32h747xx.o -mcpu=cortex-m{{.ARCH_NUMBER}} -mthumb
      - arm-none-eabi-ar rcs ../CM{{.ARCH_NUMBER}}/libs/stm32h7xx.a ./*.o
